FROM php:7.3.6-fpm-alpine3.9
# Install open ssl, bash e client mysql
RUN apk add --no-cache openssl \
    mysql-client \
    nodejs \
    npm \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev

RUN docker-php-ext-install pdo pdo_mysql

# Images handle
RUN docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include --with-png-dir=/usr/include/
RUN docker-php-ext-install -j$(nproc) gd

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www
RUN rm -rf /var/www/html
RUN ln -s public html
COPY . /var/www

RUN composer install \
             && php artisan key:generate \
             && php artisan cache:clear \
             && chmod -R 775 storage

RUN npm install

FROM php:7.3.6-fpm-alpine3.9
RUN apk add --no-cache mysql-client
RUN docker-php-ext-install pdo pdo_mysql
WORKDIR /var/www
RUN rm -rf /var/www/html
COPY --from=builder /var/www .

EXPOSE 9000
ENTRYPOINT ["php-fpm"]
